### PR TITLE
Feature/gun shooting

### PR DESCRIPTION
**Pull request by nullMeansNull**
## Additions:
Pistol (BP_Gun)
- Shooting
- Reloading
- Aiming
- Hipfire Bloom
- State Checking
- Associated structures, S_RecoilParameters and S_ShootResult

VFX
- Muzzle Flash
- Bullet Impact (Concrete)
- Bullet Impact (Flesh)

## Modifications:
BP_Player
- Ability to interface with guns

BP_FleshBeast
- Tagged as "Enemy" for comparing hit surfaces for particle effects

IMC_Default
- Added input actions for Shooting, Reloading and Aiming

HBO.uproject
- Disabled a pesky package causing me lag, shouldn't affect any systems. (UdpMessaging package)

### CODE REVIEW

**Comment by nullMeansNull** [comment]
Whatever modifications I may have accidentally made to L_Demo_PreAlpha.umap can be discarded, BP_Player needs to be compared.

**Comment by ElsFouche** [comment]
Issue:
- Blueprint Runtime Error: "Accessed None trying to read property CallFunc_BreakHitResult_HitActor_1". Node:  Branch Graph:  ShootFunc Function:  Shoot Func Blueprint:  BP_Gun
- Likely requires an 'Is Valid' node.

Issue:
- Bullet impact vfx spawns at world origin if bullet does not hit anything.

Issue: 
- `BP_Gun` is automatically in the player's hand rather than only after being collected from the environment.

**Comment by nullMeansNull** [comment]
**Correct me if up wrong,** but picking up weapons cant be implemented until my branch is merged with main so I can have the changes I believe Julian made that adds gun pickup events. Besides that, I will work on fixing the errors when not hitting anything.

**Comment by ElsFouche** [comment]
> **Correct me if up wrong,** but picking up weapons cant be implemented until my branch is merged with main so I can have the changes I believe Julian made that adds gun pickup events. Besides that, I will work on fixing the errors when not hitting anything.

When I jumped into your branch I saw Julian's work was already in there. Perhaps Github was being weird, but can I ask you to double-check on your end to see if `BP_Pistol` et al. are in your project? They should be.

**Comment by nullMeansNull** [comment]
Ah yes you are totally right, my bad. I will implement that right now.

**Review by ElsFouche — APPROVED** [review]
Overall, fantastic work. There's a few things that we'll need to change moving forward but it's not due to your work here. 
Specifically we'll need to refactor the code for collecting weapons and we should probably move the gun blueprints out of the interactable objects section since they're not really interactables, they should have their own folder. 
Additionally, it's good to avoid duplicate code when possible - how different are the pistol and shotgun? No big deal if we leave them as duplicates; it's a little inefficient but a very minor concern. 

I see that we have some conflicts however - when did those arise?

**Pull request closed without merging**
